version: '3.3'
services:
  db:
    image: postgres:13.5
    restart: always
    env_file:
      - .env
    volumes:
      - database_folder:/var/lib/postgresql/data
    networks:
      - snyt_net
  snyt-app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    ports:
      - "3030:80"
    networks:
      - snyt_net
networks:
  snyt_net:
volumes:
  database_folder:
    external:
      name: snyt_db
